[package]
name = "aptash"
version = "0.0.1"
authors = ["Sanatan sharma"]

[addresses]
aptash = "0x78dd94137dd54a26e88eca378a0255f1d22435d49cec2467a4f3c5a8cf3e70ce"  # Devnet account address

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "aptos-node-v1.15.0" }
